#!/bin/sh

python ../vanDamme.py --run_name basicRun --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/basic-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/basic.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name defendTheCenter --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/defendTheCenter-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/defend_the_center.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name healthGathering --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/healthGathering-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/health_gathering.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name deadlyCorridor --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/deadlyCorridor-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/deadly_corridor.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name myWayHome --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/myWayHome-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/my_way_home.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name defendTheLine --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/defendTheLine-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/defend_the_line.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name predictPosition --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/predictPosition-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/predict_position.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name rocketBasic --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/rocketbasic-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/rocket_basic.cfg --doom2_wad ../'Doom2.wad'
python ../vanDamme.py --run_name takeCover --save_model True --learning_steps_per_epoch 20000 --model_savefile ../models/replay20000/takeCover-100epochs-stepLearning-model.pth --epochs 100 --scenario_config ../scenarios/take_cover.cfg --doom2_wad ../'Doom2.wad'
